// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'
	| 'zh'
	| 'zh-Hans'
	| 'zh-Hant'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * T​a​g​s
	 */
	Tags: string
	/**
	 * F​i​l​t​e​r​ ​T​a​g​s​.​.​.
	 */
	FilterTags: string
	/**
	 * T​a​b​l​e​ ​o​f​ ​C​o​n​t​e​n​t
	 */
	TableOfContent: string
	/**
	 * L​o​a​d​i​n​g​ ​P​o​s​t​s​.​.​.
	 */
	LoadingPosts: string
	/**
	 * L​o​a​d​i​n​g​ ​P​o​s​t​.​.​.
	 */
	LoadingPost: string
	/**
	 * N​o​ ​P​o​s​t​ ​F​o​u​n​d​.
	 */
	NoPostFound: string
	/**
	 * L​o​a​d​i​n​g​ ​G​i​s​c​u​s​.​.​.
	 */
	LoadingGiscus: string
	/**
	 * �​�​ ​Q​W​E​R​ ​[​α​]​ ​-​ ​B​u​i​l​t​ ​w​i​t​h​ ​S​v​e​l​t​e​K​i​t​ ​a​n​d​ ​❤
	 */
	QWER: string
	/**
	 * F​i​r​s​t​ ​p​u​b​l​i​s​h​e​d​ ​a​t
	 */
	FirstPublishedAt: string
	/**
	 * L​a​s​t​ ​u​p​d​a​t​e​d​ ​a​t
	 */
	LastUpdatedAt: string
	/**
	 * U​p​d​a​t​e​d​:​ 
	 */
	Updated: string
	/**
	 * j​u​s​t​ ​n​o​w
	 */
	JustNow: string
	/**
	 * {​0​}​ ​m​i​n​u​t​e​{​{​s​}​}​ ​a​g​o
	 * @param {string | number | boolean} 0
	 */
	MinuteAgo: RequiredParams<'0'>
	/**
	 * {​0​}​ ​h​o​u​r​{​{​s​}​}​ ​a​g​o
	 * @param {string | number | boolean} 0
	 */
	HourAgo: RequiredParams<'0'>
	/**
	 * {​0​}​ ​d​a​y​{​{​s​}​}​ ​a​g​o
	 * @param {string | number | boolean} 0
	 */
	DayAgo: RequiredParams<'0'>
	/**
	 * {​0​}​ ​m​o​n​t​h​{​{​s​}​}​ ​a​g​o
	 * @param {string | number | boolean} 0
	 */
	MonthAgo: RequiredParams<'0'>
	/**
	 * {​0​}​ ​y​e​a​r​{​{​s​}​}​ ​a​g​o
	 * @param {string | number | boolean} 0
	 */
	YearAgo: RequiredParams<'0'>
	/**
	 * P​a​g​e​ ​N​o​t​ ​F​o​u​n​d
	 */
	Page404NotFound: string
	/**
	 * G​o​ ​B​a​c​k​ ​H​o​m​e​ ​!
	 */
	Page404BackHome: string
	/**
	 * S​e​a​r​c​h
	 */
	IndexSearchBox: string
	/**
	 * C​l​o​s​e
	 */
	IndexCloseSearchBox: string
}

export type TranslationFunctions = {
	/**
	 * Tags
	 */
	Tags: () => LocalizedString
	/**
	 * Filter Tags...
	 */
	FilterTags: () => LocalizedString
	/**
	 * Table of Content
	 */
	TableOfContent: () => LocalizedString
	/**
	 * Loading Posts...
	 */
	LoadingPosts: () => LocalizedString
	/**
	 * Loading Post...
	 */
	LoadingPost: () => LocalizedString
	/**
	 * No Post Found.
	 */
	NoPostFound: () => LocalizedString
	/**
	 * Loading Giscus...
	 */
	LoadingGiscus: () => LocalizedString
	/**
	 * 🚀 QWER [α] - Built with SvelteKit and ❤
	 */
	QWER: () => LocalizedString
	/**
	 * First published at
	 */
	FirstPublishedAt: () => LocalizedString
	/**
	 * Last updated at
	 */
	LastUpdatedAt: () => LocalizedString
	/**
	 * Updated: 
	 */
	Updated: () => LocalizedString
	/**
	 * just now
	 */
	JustNow: () => LocalizedString
	/**
	 * {0} minute{{s}} ago
	 */
	MinuteAgo: (arg0: string | number | boolean) => LocalizedString
	/**
	 * {0} hour{{s}} ago
	 */
	HourAgo: (arg0: string | number | boolean) => LocalizedString
	/**
	 * {0} day{{s}} ago
	 */
	DayAgo: (arg0: string | number | boolean) => LocalizedString
	/**
	 * {0} month{{s}} ago
	 */
	MonthAgo: (arg0: string | number | boolean) => LocalizedString
	/**
	 * {0} year{{s}} ago
	 */
	YearAgo: (arg0: string | number | boolean) => LocalizedString
	/**
	 * Page Not Found
	 */
	Page404NotFound: () => LocalizedString
	/**
	 * Go Back Home !
	 */
	Page404BackHome: () => LocalizedString
	/**
	 * Search
	 */
	IndexSearchBox: () => LocalizedString
	/**
	 * Close
	 */
	IndexCloseSearchBox: () => LocalizedString
}

export type Formatters = {}
