// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types.js'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import en from './en/index.js'
import ja from './ja/index.js'
import zh from './zh/index.js'
import zh_Hans from './zh-Hans/index.js'
import zh_Hant from './zh-Hant/index.js'

const localeTranslations = {
	en,
	ja,
	zh,
	'zh-Hans': zh_Hans,
	'zh-Hant': zh_Hant,
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
